spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/idrisdatabase}
    username: ${DB_USER:ai222829}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 8080
